import { ArrowRight, Check, CircleDollarSign, Database, Plus, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import type { ResearchOverview, XAccount } from '../../shared/contracts'
import { api } from '../api'
import { Button } from '../components/Button'
import { EmptyState } from '../components/EmptyState'
import { useSession } from '../components/SessionProvider'

export function DashboardPage(){
  const {session}=useSession(); const [accounts,setAccounts]=useState<XAccount[]>([]); const [research,setResearch]=useState<ResearchOverview>({sources:[],targets:[],items:[]}); const [loading,setLoading]=useState(true)
  useEffect(()=>{Promise.all([api<XAccount[]>('/accounts'),api<ResearchOverview>('/research/overview')]).then(([a,r])=>{setAccounts(a);setResearch(r)}).finally(()=>setLoading(false))},[])
  if(!session)return null
  return <><div className="page-heading"><div><p className="eyebrow">PHASE 2 · RESEARCH & X VIEWER</p><h1>ダッシュボード</h1><p>3アカウントの基盤とResearch Poolを一つの運用OSで管理します。</p></div><Link to="/research"><Button icon={<Plus size={16}/>}>リサーチを追加</Button></Link></div>
  <section className="stat-grid"><article className="stat-card"><div className="stat-card__top"><span>登録アカウント</span><Users size={18}/></div><strong>{session.limits.activeAccountCount}<small> / {session.limits.accountLimit}</small></strong><p>個人MVPの登録上限</p></article><article className="stat-card"><div className="stat-card__top"><span>Research Items</span><Database size={18}/></div><strong>{research.items.length}</strong><p>{research.sources.length} Sources / {research.targets.length} Targets</p></article><article className="stat-card"><div className="stat-card__top"><span>外部APIコスト</span><CircleDollarSign size={18}/></div><strong>¥0</strong><p>Phase 2はX API / AI API未使用</p></article><article className="stat-card"><div className="stat-card__top"><span>開発フェーズ</span><span className="phase-dot">2</span></div><strong>2 / 5</strong><p>Research & X Viewer</p></article></section>
  <div className="dashboard-grid"><section className="panel"><div className="panel__heading"><div><h2>運用アカウント</h2><p>Strategy / Voiceをアカウントごとに分離。</p></div><Link className="text-link" to="/accounts">すべて見る <ArrowRight size={14}/></Link></div>{loading?<div className="card-skeletons"><div className="skeleton skeleton--card"/></div>:accounts.length===0?<EmptyState icon={<Users size={24}/>} title="アカウントはまだありません" description="最初のXアカウントを登録してください。"/>:<div className="account-summary-list">{accounts.slice(0,3).map(a=><Link to={`/accounts?edit=${a.id}`} className="account-summary" key={a.id}><span className="avatar avatar--lg">{a.displayName.slice(0,1).toUpperCase()}</span><span className="account-summary__main"><strong>{a.displayName}</strong><small>@{a.handle}</small></span><ArrowRight size={16}/></Link>)}</div>}</section><section className="panel"><div className="panel__heading"><div><h2>Phase 2 完了条件</h2><p>API課金なしでResearch運用を成立させます。</p></div></div><ul className="check-list"><li className="check-list__done"><Check size={16}/><span>Shared Research Pool</span></li><li className="check-list__done"><Check size={16}/><span>RSS / Web / Manual Source</span></li><li className="check-list__done"><Check size={16}/><span>Competitor / Target registry</span></li><li className="check-list__done"><Check size={16}/><span>X公式公開Embed Viewer</span></li></ul><div className="phase-note"><strong>次は Phase 3</strong><p>Research → Angle → Draft → Human ReviewをAI Provider Adapterで実装します。</p></div></section></div></>
}
